development:
  adapter: mysql2
  database: tcr1 
  pool: 5
  host: localhost
  password: tcr
  encoding: utf8
  timeout: 5000
production:
  adapter: mysql2
  database: tcr1 
  pool: 5
  host: localhost
  password: tcr 
  encoding: utf8
  timeout: 5000

